export const ALL_NOTES = "http://localhost:5000/api/v1/notes"
export const CREATE_NOTE = "http://localhost:5000/api/v1/notes/create"
export const DELETE_NOTES = "http://localhost:5000/api/v1/notes/delete"
export const DETAIL_NOTE = "http://localhost:5000/api/v1/notes/detail"
export const UPDATE_NOTE = "http://localhost:5000/api/v1/notes/update"